apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaves-deployment
  labels:
    app: leaves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaves
  template:
    metadata:
      labels:
        app: leaves
    spec:
      containers:
        - name: leaves
          image: mandeepbsaini350/batman:2.0.0
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: LEAVES_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-deployment:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: leaves
spec:
  selector:
    app: leaves
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090