apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: payroll-configmap
                  key: POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  selector:
    app: postgres-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432