server:
  port: 9000
spring:
  application:
    name: salary
  config:
    import: "optional:configserver:http://configserver:8071"
  profile:
    active: "prod"
#  datasource:
#    url: jdbc:h2:mem:salarydb
#    username: sa
#    password: ""
#    driverClassName: org.h2.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://postgres-deployment:5432/postgres
    username: postgres
    password: 2001
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #  h2:
    #    console:
    #      enabled: true
    #      path: /h2-console
    transaction:
      rollback-on-commit-failure: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eurekaserver:8070/eureka/"

info:
  app:
    name: "Salary MS"
    description: "Salary MS for Payroll"
    version : "1.0.0"
springdoc:
  swagger-ui:
    path: /swagger-ui.html